name: replace-in-files
files:
  - "src/**/*.ts"
  - ".*"
  - "*"
  - "!node_modules"
  - "!rif.config.yaml"
replacements:
  - from: /typescript-tsup-library-description/g
    to: Get url from weibo pid.
  - from: /typescript-tsup-library/g
    to: ${PROJECT_NAME}
  - from: /SCOPE/gi
    to: "@jswork"
  - from: /tsupLibrary/g
    to: WeiboPid2url
